version: '2.3'

services:
  # SERVICE: cli
  cli:
    networks:
      - amazeeio-network
      - default
    build:
      context: .
      dockerfile: lagoon/cli.dockerfile
    image: &cli-image cli-cli 
    labels:
      lagoon.type: cli-persistent
      lagoon.persistent.name: nginx
      lagoon.persistent: /app/web/storage
    volumes_from: 
      - container:amazeeio-ssh-agent
    environment:
      LAGOON_PROJECT: aio-php-bench
      LAGOON_ROUTE: http://aio-php-bench.docker.amazee.io
      LAGOON_ENVIRONMENT: local


 # SERVICE: nginx
  nginx:
    networks:
      - amazeeio-network
      - default
    build:
      context: .
      dockerfile: lagoon/nginx.dockerfile
    labels:
      lagoon.type: nginx-php-persistent
      lagoon.name: nginx
      lagoon.persistent: /app/web/storage
    environment:
      LAGOON_PROJECT: aio-php-bench
      LAGOON_ROUTE: http://aio-php-bench.docker.amazee.io
      LAGOON_ENVIRONMENT: local

  # SERVICE: php 
  php:
    networks:
      - amazeeio-network
      - default
    build:
      context: .
      dockerfile: lagoon/php.dockerfile
    labels:
      lagoon.type: nginx-php-persistent
      lagoon.name: nginx
      lagoon.persistent: /app/web/storage/
    environment:
      LAGOON_PROJECT: aio-php-bench
      LAGOON_ROUTE: http://aio-php-bench.docker.amazee.io
      LAGOON_ENVIRONMENT: local

networks:
  amazeeio-network:
    external: true

